Fixes #9 - Error: undefined method `[]' for true:TrueClass
PROBLEM

The instructions given for the [Usage](https://github.com/octopress/paginate#usage) page doesn't work after Octopress [Initial setup](http://octopress.org/docs/setup/).

CAUSE

Configuring Octopress as described at [Initial setup](http://octopress.org/docs/setup/) leads to a `_config.yml` which contains the two lines:

    paginate: 10          # Posts per page on the blog index
    paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/

these two keys conflict in some way with the configuration ones used by this plugin.

SOLUTION

I've added the subsection `Remove Octopress pagination defaults` in which is suggested to remove the two lines.

octopress/paginate#9